name: GoJekTakeHome
options:
  bundleIdPrefix: com.rmalhotra
targets:
  GoJekTakeHome:
    type: application
    platform: [iOS]
    sources: GoJekTakeHome
    scheme:
      gatherCoverageData: true
      testTargets:
        - GoJekTakeHomeTests_$platform
  GoJekTakeHomeTests:
    type: bundle.unit-test
    platform: [iOS]
    sources: GoJekTakeHomeTests
    dependencies:
      - target: GoJekTakeHomeTests_$platform